### ISSUE TITLE
Merge Environment variables, not replace

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/launcher#53]
Version 1.0.5 replaces the environment variables that exist in the Docker image, this breaks Go and Node containers.

We should be merging the environment instead of replacing it.

**Comment by jer** [comment]
Weird. I wonder what sequence of characters we could type to resolve this.

**Comment by Filbird** [comment]
Overwrite in the sense that the only environment variables left available
are those specified in the Job, or that  envrionment variables of the same
name being overwritten by those in the Job?

**Comment by stjohnjohnson** [comment]
The environment that's already available when the launcher runs should be merged with the environment settings that are passed from the validate api.  That way the built-in env from the build container still applies and users can override those variables if they want.

**Comment by jer** [comment]
Specifically, the command should take the current environment in the launcher (os.Environ), and it should add the Job's environment, overwriting where there are collisions. The result of this combination should be cmd.Env

**Comment by stjohnjohnson** [comment]
Fixed :)
